insert into topics (id, name, icon, color, difficulty, progress) values
('algebra', 'Algebra', '📐', '#7c5cfc', 'Medium', 72),
('biology', 'Biology', '🧬', '#34d399', 'Hard', 45),
('spanish', 'Spanish', '🇪🇸', '#fb923c', 'Easy', 88),
('history', 'World History', '🏛️', '#facc15', 'Medium', 60),
('physics', 'Physics', '⚛️', '#f87171', 'Hard', 33),
('chemistry', 'Chemistry', '🧪', '#a78bfa', 'Medium', 55),
('economics', 'Economics', '📈', '#38bdf8', 'Medium', 40);

insert into questions (topic_id, position, question_text, options, answer, explanation) values
('algebra', 0, 'Solve for x: 2x + 6 = 14', '["x = 3","x = 4","x = 5","x = 8"]', 1, 'Subtract 6: 2x = 8, then divide by 2: x = 4.'),
('algebra', 1, 'What is 3² + 4²?', '["12","24","25","7"]', 2, '9 + 16 = 25.'),
('algebra', 2, 'Simplify: 2(3x + 4) - x', '["5x + 8","6x + 4","5x + 4","6x + 8"]', 0, '6x + 8 - x = 5x + 8.'),
('algebra', 3, 'If f(x) = 2x - 3, what is f(5)?', '["7","10","13","5"]', 0, '2(5) - 3 = 7.'),
('algebra', 4, 'What is the slope of y = -3x + 7?', '["3","-3","7","-7"]', 1, 'Slope m = -3.'),
('algebra', 5, 'Factor: x² - 9', '["(x-3)(x+3)","(x-9)(x+1)","(x-3)²","(x+3)²"]', 0, 'Difference of squares.'),
('algebra', 6, 'Solve: |x - 4| = 7', '["x = 11 only","x = -3 only","x = 11 or x = -3","x = 3 or x = -11"]', 2, 'x - 4 = 7 → 11, or x - 4 = -7 → -3.'),
('algebra', 7, 'What is log₂(32)?', '["4","5","6","16"]', 1, '2⁵ = 32.'),
('algebra', 8, 'Simplify: (x³)²', '["x⁵","x⁶","x⁹","x⁸"]', 1, 'Multiply exponents: 3×2 = 6.'),
('algebra', 9, 'Roots of x² - 5x + 6 = 0?', '["x = 1, 6","x = 2, 3","x = -2, -3","x = 1, 5"]', 1, '(x-2)(x-3) = 0.'),

('biology', 0, 'Powerhouse of the cell?', '["Nucleus","Ribosome","Mitochondria","Golgi apparatus"]', 2, 'Mitochondria produce ATP.'),
('biology', 1, 'DNA stands for:', '["Deoxyribonucleic Acid","Dinitrogen Acid","Deoxyribose Nucleic Agent","Dynamic Nuclear Acid"]', 0, 'Deoxyribonucleic Acid.'),
('biology', 2, 'Basic unit of life?', '["Atom","Molecule","Cell","Organ"]', 2, 'The cell.'),
('biology', 3, 'Photosynthesis organelle?', '["Mitochondria","Chloroplast","Vacuole","Lysosome"]', 1, 'Chloroplasts.'),
('biology', 4, 'Bond holding DNA strands?', '["Ionic","Hydrogen","Covalent","Metallic"]', 1, 'Hydrogen bonds between base pairs.'),
('biology', 5, 'Cell division in body cells?', '["Meiosis","Mitosis","Binary fission","Cytokinesis"]', 1, 'Mitosis.'),
('biology', 6, 'Oxygen carrier in blood?', '["White blood cells","Plasma","Hemoglobin","Platelets"]', 2, 'Hemoglobin.'),
('biology', 7, 'Outermost layer of animal cell?', '["Cell wall","Cell membrane","Nuclear membrane","Cytoplasm"]', 1, 'Cell membrane.'),
('biology', 8, 'Sugar in RNA?', '["Glucose","Deoxyribose","Ribose","Fructose"]', 2, 'Ribose.'),
('biology', 9, 'Kingdom of mushrooms?', '["Plantae","Animalia","Fungi","Protista"]', 2, 'Fungi.'),

('spanish', 0, '"Hello" in Spanish?', '["Adiós","Hola","Gracias","Por favor"]', 1, 'Hola.'),
('spanish', 1, '"Gracias" means:', '["Please","Sorry","Thank you","Goodbye"]', 2, 'Thank you.'),
('spanish', 2, '"The book":', '["El libro","La libro","Los libro","El libros"]', 0, 'Libro is masculine.'),
('spanish', 3, 'Past tense of "hablar":', '["Hablo","Hablaré","Habló","Hablando"]', 2, 'Habló.'),
('spanish', 4, '"Yo tengo hambre":', '["I am tired","I am hungry","I am thirsty","I am happy"]', 1, 'I am hungry.'),
('spanish', 5, '"Perro" means:', '["Cat","Bird","Dog","Fish"]', 2, 'Dog.'),
('spanish', 6, '"Ser" for "yo":', '["Eres","Soy","Es","Somos"]', 1, 'Yo soy.'),
('spanish', 7, '"Good night":', '["Buenos días","Buenas tardes","Buenas noches","Bueno noche"]', 2, 'Buenas noches.'),
('spanish', 8, '"¿Dónde está el baño?":', '["Kitchen","Bathroom","Bedroom","Exit"]', 1, 'Where is the bathroom?'),
('spanish', 9, 'Plural of "ciudad":', '["Ciudads","Ciudades","Ciudadós","Ciudade"]', 1, 'Add "-es".'),

('history', 0, 'WWII ended in:', '["1943","1944","1945","1946"]', 2, '1945.'),
('history', 1, 'First US President?', '["Jefferson","Adams","Washington","Franklin"]', 2, 'George Washington.'),
('history', 2, 'Renaissance began in:', '["France","England","Italy","Spain"]', 2, 'Italy.'),
('history', 3, 'Ancient wonder in Giza?', '["Hanging Gardens","Colossus","Great Pyramid","Lighthouse"]', 2, 'Great Pyramid.'),
('history', 4, '"I Have a Dream" by:', '["Malcolm X","MLK Jr.","JFK","Rosa Parks"]', 1, 'Martin Luther King Jr.'),
('history', 5, 'French Revolution began:', '["1776","1789","1799","1804"]', 1, '1789.'),
('history', 6, 'Empire that built Machu Picchu?', '["Aztec","Maya","Inca","Olmec"]', 2, 'Inca.'),
('history', 7, 'Wall that fell in 1989?', '["Great Wall","Hadrian''s","Berlin Wall","Wailing Wall"]', 2, 'Berlin Wall.'),
('history', 8, 'Penicillin discovered by?', '["Pasteur","Fleming","Lister","Koch"]', 1, 'Alexander Fleming.'),
('history', 9, 'Industrial Revolution started in:', '["Germany","France","US","Great Britain"]', 3, 'Great Britain.'),

('physics', 0, 'Speed of light?', '["300,000 km/s","150,000 km/s","300,000 m/s","1,000,000 km/s"]', 0, '~300,000 km/s.'),
('physics', 1, 'E = mc² describes:', '["Kinetic energy","Mass-energy equivalence","Gravity","Ohm''s law"]', 1, 'Mass-energy equivalence.'),
('physics', 2, 'SI unit of force?', '["Joule","Watt","Newton","Pascal"]', 2, 'Newton.'),
('physics', 3, 'Newton''s First Law?', '["Acceleration","Inertia","Action-reaction","Gravity"]', 1, 'Inertia.'),
('physics', 4, 'Negative charge particle?', '["Proton","Neutron","Electron","Photon"]', 2, 'Electron.'),
('physics', 5, 'Gravity on Earth?', '["8.9 m/s²","9.8 m/s²","10.8 m/s²","6.7 m/s²"]', 1, '9.8 m/s².'),
('physics', 6, 'Energy conservation law?', '["1st Law of Thermo","2nd Law of Thermo","Conservation of Momentum","Heisenberg"]', 0, '1st Law of Thermodynamics.'),
('physics', 7, 'Sound is what wave?', '["Transverse","Longitudinal","Electromagnetic","Surface"]', 1, 'Longitudinal.'),
('physics', 8, 'Kinetic energy formula?', '["mgh","½mv²","Fd","PV"]', 1, '½mv².'),
('physics', 9, 'General relativity by?', '["Newton","Einstein","Hawking","Bohr"]', 1, 'Einstein.'),

('chemistry', 0, 'Chemical symbol for water?', '["HO","H₂O","OH₂","H₃O"]', 1, 'H₂O.'),
('chemistry', 1, 'Atomic number of Carbon?', '["4","6","8","12"]', 1, '6.'),
('chemistry', 2, 'pH of neutral substance?', '["0","7","14","1"]', 1, '7.'),
('chemistry', 3, 'Noble gas?', '["Nitrogen","Oxygen","Neon","Hydrogen"]', 2, 'Neon.'),
('chemistry', 4, 'NaCl is:', '["Sugar","Baking soda","Table salt","Vinegar"]', 2, 'Table salt.'),
('chemistry', 5, 'Bonds carbon can form?', '["2","3","4","6"]', 2, '4.'),
('chemistry', 6, 'Gas plants absorb?', '["Oxygen","Nitrogen","CO₂","Hydrogen"]', 2, 'Carbon dioxide.'),
('chemistry', 7, 'Isotope = same element, different?', '["Protons","Neutrons","Mass","An ion"]', 1, 'Neutrons.'),
('chemistry', 8, 'Fixed shape state?', '["Gas","Liquid","Solid","Plasma"]', 2, 'Solid.'),
('chemistry', 9, 'Reaction releasing energy?', '["Endothermic","Exothermic","Synthesis","Decomposition"]', 1, 'Exothermic.'),

('economics', 0, 'What is GDP?', '["Gross Domestic Product","General Demand Price","Government Debt Plan","Global Distribution Protocol"]', 0, 'Gross Domestic Product.'),
('economics', 1, 'Inflation is:', '["Decrease in prices","General increase in prices","Stable prices","Decrease in supply"]', 1, 'General increase in prices.'),
('economics', 2, 'Supply and demand is:', '["Government policy","Price determination model","A tax","A banking system"]', 1, 'Price determination model.'),
('economics', 3, 'Recession =:', '["Economic boom","Economic decline","Rapid inflation","Trade surplus"]', 1, 'Economic decline.'),
('economics', 4, 'Central bank does:', '["Prints money","Sets monetary policy","Collects taxes","Builds infrastructure"]', 1, 'Sets monetary policy.'),
('economics', 5, 'Opportunity cost is:', '["Production cost","Value of next best alternative","Labor cost","Gov spending"]', 1, 'Value of next best alternative.'),
('economics', 6, 'Monopoly:', '["Competitive market","Single seller dominates","A tax","Trade agreement"]', 1, 'Single seller dominates.'),
('economics', 7, 'Fiscal policy:', '["Interest rates","Gov spending & taxation","Trade regulation","Banking regulation"]', 1, 'Gov spending & taxation.'),
('economics', 8, 'Tariff:', '["Subsidy","Tax on imports","Trade agreement","Currency"]', 1, 'Tax on imports.'),
('economics', 9, 'Budget deficit:', '["Spend < revenue","Spend > revenue","Balanced","Zero spending"]', 1, 'Spend > revenue.'),
('economics', 10, 'Law of demand:', '["Price↑ demand↑","Price↑ demand↓","Supply determines","Fixed demand"]', 1, 'Price↑ demand↓.'),
('economics', 11, 'Market economy:', '["Gov controls all","Supply & demand driven","No trade","Only agriculture"]', 1, 'Supply & demand driven.'),
('economics', 12, 'Trade deficit:', '["Exports > imports","Imports > exports","Balanced","No trade"]', 1, 'Imports > exports.'),
('economics', 13, 'Economic indicator:', '["Stock price","Stat measuring health","A bond","Gov agency"]', 1, 'Stat measuring health.'),
('economics', 14, 'Elasticity:', '["A tax","Demand responsiveness to price","Flexibility","Stability"]', 1, 'Demand responsiveness to price.'),
('economics', 15, 'Unemployment:', '["Full employment","Without job, seeking work","Part-time","Retirement"]', 1, 'Without job, seeking work.'),
('economics', 16, 'Stock:', '["A bond","Ownership share in company","A loan","Currency"]', 1, 'Ownership share in company.'),
('economics', 17, 'GDP per capita:', '["Total GDP","GDP / population","GDP - debt","GDP growth"]', 1, 'GDP / population.'),
('economics', 18, 'Externality:', '["Internal cost","Side effect on third parties","A tax","Intl trade"]', 1, 'Side effect on third parties.'),
('economics', 19, 'Inflation targeting:', '["Eliminate it","Central bank keeps inflation at set level","Cause deflation","Ignore prices"]', 1, 'Central bank keeps inflation at set level.'),
('economics', 20, 'Comparative advantage:', '["More resources","Lower opportunity cost","Biggest producer","Cheaper labor"]', 1, 'Lower opportunity cost.'),
('economics', 21, 'Mixed economy:', '["Pure capitalism","Pure communism","Market + gov intervention","No economy"]', 2, 'Market + gov intervention.'),
('economics', 22, 'Consumer surplus:', '["Extra profit","Willingness to pay - actual pay","Gov subsidy","Unused budget"]', 1, 'Willingness to pay - actual pay.'),
('economics', 23, 'Multiplier effect:', '["Currency multiply","Initial spending → larger impact","Interest compounding","Tax calc"]', 1, 'Initial spending → larger impact.'),
('economics', 24, 'Hyperinflation:', '["Mild inflation","Extremely rapid price increases","Deflation","Stable prices"]', 1, 'Extremely rapid price increases.');
